# Generated by Django 4.2.21 on 2025-05-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封禁到期时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='是否被封禁'),
        ),
    ]
