version: '3.8'

# 这个 docker-compose 文件提供了一个完全独立的运行环境。
# 它会创建一个专属的 Redis 容器，不需要任何外部依赖。
# 使用 'docker-compose -f docker-compose.standalone.yml up -d' 来启动。

services:
  web:
    image: cetaceang/my-chatbox:latest
    container_name: my-chatbox-web-standalone
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data/db.sqlite3:/app/db.sqlite3
    env_file:
      - .env.docker
    environment:
      # 连接到下面定义的 redis 服务
      - REDIS_HOST=redis
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - redis
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 3000 config.asgi:application"

  redis:
    image: redis:latest
    container_name: my-chatbox-redis-standalone
    restart: unless-stopped
    volumes:
      # 可选：如果你希望 Redis 数据持久化，可以取消下面的注释
      # - ./redis_data:/data
