# Generated by Django 5.2.1 on 2025-05-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_aimodel_aiprovider_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='default_params',
            field=models.JSONField(blank=True, default=dict, verbose_name='默认参数'),
        ),
    ]
