# Generated by Django 4.2.21 on 2025-05-25 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_aimodel_default_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='sync_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='同步标识符'),
        ),
    ]
