# Generated by Django 4.2.21 on 2025-05-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_conversation_sync_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_generation_id',
            field=models.UUIDField(blank=True, editable=False, help_text='当前正在处理的API生成的唯一ID', null=True),
        ),
    ]
