# Generated by Django 4.2.21 on 2025-07-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_current_generation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='system_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='系统提示词'),
        ),
    ]
