# Generated by Django 4.2.23 on 2025-09-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_conversation_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='generation_id',
            field=models.UUIDField(blank=True, help_text='与此消息相关的生成事件的唯一ID', null=True),
        ),
    ]
